package pl.pmuflon.busted;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLANNED_INVOICE.
 */
public class PlannedInvoice {

    private Long id;
    /** Not-null value. */
    private String name;
    private float amount;
    /** Not-null value. */
    private java.util.Date date;
    /** Not-null value. */
    private String periodicity;

    public PlannedInvoice() {
    }

    public PlannedInvoice(Long id) {
        this.id = id;
    }

    public PlannedInvoice(Long id, String name, float amount, java.util.Date date, String periodicity) {
        this.id = id;
        this.name = name;
        this.amount = amount;
        this.date = date;
        this.periodicity = periodicity;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public float getAmount() {
        return amount;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getPeriodicity() {
        return periodicity;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPeriodicity(String periodicity) {
        this.periodicity = periodicity;
    }

}
