package pl.pmuflon.busted;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import pl.pmuflon.busted.PlannedInvoice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLANNED_INVOICE.
*/
public class PlannedInvoiceDao extends AbstractDao<PlannedInvoice, Long> {

    public static final String TABLENAME = "PLANNED_INVOICE";

    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Amount = new Property(2, float.class, "amount", false, "AMOUNT");
        public final static Property Date = new Property(3, java.util.Date.class, "date", false, "DATE");
        public final static Property Periodicity = new Property(4, String.class, "periodicity", false, "PERIODICITY");
    };


    public PlannedInvoiceDao(DaoConfig config) {
        super(config);
    }
    
    public PlannedInvoiceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String sql = "CREATE TABLE " + (ifNotExists? "IF NOT EXISTS ": "") + "'PLANNED_INVOICE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT NOT NULL ," + // 1: name
                "'AMOUNT' REAL NOT NULL ," + // 2: amount
                "'DATE' INTEGER NOT NULL ," + // 3: date
                "'PERIODICITY' TEXT NOT NULL );"; // 4: periodicity
        db.execSQL(sql);
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLANNED_INVOICE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlannedInvoice entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindDouble(3, entity.getAmount());
        stmt.bindLong(4, entity.getDate().getTime());
        stmt.bindString(5, entity.getPeriodicity());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlannedInvoice readEntity(Cursor cursor, int offset) {
        PlannedInvoice entity = new PlannedInvoice( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getFloat(offset + 2), // amount
            new java.util.Date(cursor.getLong(offset + 3)), // date
            cursor.getString(offset + 4) // periodicity
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlannedInvoice entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setAmount(cursor.getFloat(offset + 2));
        entity.setDate(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setPeriodicity(cursor.getString(offset + 4));
     }
    
    @Override
    protected Long updateKeyAfterInsert(PlannedInvoice entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PlannedInvoice entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
